window.JOBS = [
  {
    id: 1,
    company: "ABC Tech",
    title: "MES 시스템 개발자",
    location: "창원",
    career: "3년 이상",
    category: "개발",
    employment: "정규직",
    skills: ["Java", "Oracle", "MES", "Spring Boot"],
    duties: ["제조 MES 시스템 개발 및 유지보수", "현장 요구사항 반영 및 화면 개선", "Oracle DB 연동 및 쿼리 작성"],
    requirements: ["Java / Oracle 활용 가능", "업무 시스템 운영 경험", "문제 해결 및 협업 역량"],
    preferred: ["Spring Boot 경험", "MES / ERP 경험", "제조업 시스템 이해"],
    deadline: "상시채용"
  },
  {
    id: 2,
    company: "XYZ Solution",
    title: "웹 백엔드 개발자",
    location: "부산",
    career: "2년 이상",
    category: "개발",
    employment: "정규직",
    skills: ["Java", "Spring Boot", "MySQL", "REST API"],
    duties: ["웹 서비스 API 개발", "서비스 운영 및 장애 대응", "DB 모델링 및 성능 개선"],
    requirements: ["Java 또는 Kotlin 경험", "REST API 이해", "RDB 사용 경험"],
    preferred: ["AWS 경험", "CI/CD 경험", "협업 프로젝트 경험"],
    deadline: "2026-09-15"
  },
  {
    id: 3,
    company: "Future IT",
    title: "사내 전산 운영",
    location: "울산",
    career: "신입~3년",
    category: "IT지원",
    employment: "정규직",
    skills: ["IT지원", "Network", "OA", "Helpdesk"],
    duties: ["사내 PC 및 계정 관리", "네트워크 장애 1차 대응", "IT 자산 및 라이선스 관리"],
    requirements: ["Windows 환경 이해", "사용자 커뮤니케이션 역량", "기초 네트워크 지식"],
    preferred: ["전산 관련 자격증", "M365 관리 경험", "네트워크 장비 운영 경험"],
    deadline: "2026-09-01"
  },
  {
    id: 4,
    company: "Smart Factory",
    title: "생산시스템 운영",
    location: "김해",
    career: "2년 이상",
    category: "MES/ERP",
    employment: "정규직",
    skills: ["MES", "ERP", "SQL", "운영"],
    duties: ["생산시스템 운영 및 모니터링", "현장 사용자 지원", "데이터 오류 분석"],
    requirements: ["SQL 활용", "업무 시스템 운영 경험", "제조 프로세스 이해"],
    preferred: ["MES 구축 경험", "Oracle 경험", "PLC 데이터 연동 이해"],
    deadline: "채용시 마감"
  },
  {
    id: 5,
    company: "Data Works",
    title: "데이터 분석 주니어",
    location: "대구",
    career: "신입",
    category: "데이터",
    employment: "정규직",
    skills: ["Python", "Pandas", "SQL", "BI"],
    duties: ["데이터 전처리", "리포트 자동화", "대시보드 지표 관리"],
    requirements: ["Python 기초", "SQL 기초", "데이터 시각화 관심"],
    preferred: ["Pandas 프로젝트", "Power BI 경험", "통계 기초"],
    deadline: "2026-09-20"
  },
  {
    id: 6,
    company: "CloudOne",
    title: "클라우드 엔지니어",
    location: "서울",
    career: "1년 이상",
    category: "인프라",
    employment: "정규직",
    skills: ["Linux", "AWS", "Python", "Infra"],
    duties: ["클라우드 인프라 운영", "서버 모니터링", "운영 자동화"],
    requirements: ["Linux 운영 경험", "네트워크 기초", "스크립트 작성 경험"],
    preferred: ["AWS 자격증", "Terraform 경험", "Docker 경험"],
    deadline: "2026-09-12"
  },
  {
    id: 7,
    company: "Factory Digital",
    title: "스마트팩토리 개발자",
    location: "창원",
    career: "3년 이상",
    category: "개발",
    employment: "정규직",
    skills: ["Java", "MES", "Oracle", "PLC"],
    duties: ["스마트팩토리 시스템 개발", "설비 데이터 연계", "생산실적 화면 개발"],
    requirements: ["Java 개발 경험", "Oracle SQL", "제조 시스템 이해"],
    preferred: ["PLC 통신 경험", "Android 개발 경험", "Spring Boot 경험"],
    deadline: "2026-09-30"
  },
  {
    id: 8,
    company: "Busan Systems",
    title: "IT 운영 및 시스템 개발",
    location: "부산",
    career: "3년 이상",
    category: "IT지원",
    employment: "정규직",
    skills: ["Java", "Oracle", "Network", "ERP"],
    duties: ["사내 시스템 유지보수", "전산 인프라 운영", "사용자 요구사항 개발"],
    requirements: ["업무 시스템 개발 경험", "DB 쿼리 가능", "IT 운영 경험"],
    preferred: ["제조업 경험", "네트워크 장비 운영 경험", "Python 자동화 경험"],
    deadline: "채용시 마감"
  }
];
